# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07c45472e442b0f9538c9c673dd15074f721389e5ebcf783dcf62ae1196d4b7d08b39ac3a13d158c0c8fe5e857b38f3f5570ea1506474942aeaeac0ef6f85966

test:
  secret_key_base: 2870c90ba143a71bf293dfcb099703a6af75f1ae1908dacbaae798f739cd67878795f4c4d1570082d28bc381a24d9b8e9e73292ad1b0cc15a85b13a6741d7e22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
